### ISSUE TITLE
Idea: Support for wallpaper slideshows

### ISSUE THREAD

**Issue by mleko69** [Zren/plasma-wallpapers#1]
This wallapaper blur plugin is so amazing. Possibility to use slideshows would make it even more sexy! :)

Also I've noticed  a bug: alt-tabbing windows turns off the blur. Moving active window by at least 1px enables the blur again.

_Screen 1. Proof of bug_
![screenshot_20180105_180535](https://user-images.githubusercontent.com/22177132/34619696-4cef69ea-f243-11e7-8fcb-184151e33c69.png)

_Screen 2. Moving active window turns the blur on again_
![screenshot_20180105_180552](https://user-images.githubusercontent.com/22177132/34619730-67a9df40-f243-11e7-8478-b127a5b8f83a.png)

**Comment by Zren** [comment]
I can't seem to reproduce.

https://streamable.com/8c2jg

Last I checked, the slideshow wallpaper either had a cpu bug or memory leak in Qt 5.9+, so I wouldn't be able to copy the existing code straight from it. That said, it wouldn't be too hard to workaround.

The slideshow does a fade between images using a complex animation.

https://github.com/KDE/plasma-workspace/blob/master/wallpapers/image/imagepackage/contents/ui/main.qml#L183-L227

A simpler animation could be done. A "fade to black" then swaps image then "fade in" might be possible.

The whole reason the bug exists is that it's using ParallelAnimation... I think. I'm fairly certain SequentialAnimation by itself would probably be okay.

**Comment by Zren** [comment]
Implemented in v2.
