### ISSUE TITLE
ms setting to blur over a certain time keeps resetting to 0ms

### ISSUE THREAD

**Issue by ghost** [Zren/plasma-wallpapers#3]
Setting the MS setting to blur to chosen % over a certain time keeps resetting to 0ms upon clicking Apply.

**Comment by Zren** [comment]
What version of Plasma? It works fine for me in Plasma 5.15.3.

**Comment by ghost** [comment]
Hey Zren - I'm running KDE 5.56.0 / Plasma 5.15.3.

I've noticed that if I tab over from the "%" field, to the MS field, it stays the same. If i click into the field, and set it to anything then click Apply, it reverts back to 0ms.

I've got it working now but I have to click into the fist field, tab to the ms, and enter the number (not use the up / down buttons).

**Comment by Zren** [comment]
I can reproduce it using the up/down buttons when going from `0ms` to `100ms` using the spinbox up/down buttons. It doesn't reset to 0ms every time we test though, so there's some sort of race condition.

Looks like I need to set `QQC2.SpinBox.valueFromText()` after overriding `textFromValue()`.

* https://doc.qt.io/qt-5/qml-qtquick-controls2-spinbox.html#valueFromText-prop
* https://doc.qt.io/qt-5/qml-qtquick-controls2-spinbox.html#textFromValue-prop

**Comment by dlakatos847** [comment]
Still an issue with KDE 5.62.0, Plasma 5.16.5 on OpenSuSE Tumbleweed. @RavenTheDev 's workaround is the only way to set anything else than 0ms.

**Comment by Zren** [comment]
Should be fixed in inactiveblur v4 or v5. v5 requires KDE Frameworks v5.53+ (Ubuntu 19.04).

**Comment by dlakatos847** [comment]
Okay, i have v3. That explains why I still have the problem. For some reason, KDE Plasma 5 only shows Inactive Blur v3 as a downloadable version.
